version: '3'

services:

  nginx:
    image: nginx
    container_name: web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
      - ../../runningdinner/runningdinner-client/packages/webapp/build:/usr/share/nginx/html
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem
    extra_hosts:
      - "runningdinner-backend:${DOCKER_HOST_IP}"

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres13
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-13:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD=root

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      #      - DEBUG=${DEBUG-}
      - DEBUG=1
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres-data-13:
